spring:
  application:
    name: Spring REST API based on CQRS
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cqrs?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false&allowPublicKeyRetrieval=true
    name: MySQL Connection
    username: root
    password: root
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: MYSQL
    show_sql: true
    properties:
      hibernate:
        format_sql: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
    hibernate:
      ddl-auto: none
  jackson:
    serialization:
      write_dates_as_timestamps: false
server:
  servlet:
    context-path: /api
  port: 8080
debug: false
